# Dockerfile.frontend
FROM node:18

WORKDIR /app

COPY . /app/

RUN npm install
RUN npm run build

# Servir a aplicação com o serve
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
