version: '3.9'

services:
  backend:
    build:
      context: ./django-backend/PharmaClinic
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./django-backend/PharmaClinic:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
